name: CI/CD

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  setup-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
      - uses: actions/checkout@v2
      - name: Setup python 3.8
        uses: actions/setup-python@v2
        with:
            python-version: '3.8'
      - name: Install deps
        run: |
          python3.8 -m pip install --upgrade pip
          python3.8 -m pip install -r requirements.txt
        
  
  test:
    runs-on: ubuntu-latest
    needs: [setup-python]
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          pip install -e '.[test]'
          python3.8 -m coverage run -m pytest
          python3.8 -m coverage report

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: build image
      run: docker build -t flask_app:v0.1 -f Dockerfile .  
      
    - name: push to docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mushka/devops-back
        dockerfile: Dockerfile
        tags: latest
      
    - name: run container
      run: docker run -d -p 5000:5000 flask_app:v0.1

  telegram_notification:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_TO }}
          token: ${{ secrets.TG_TOKEN }}
          message: All checks passed
